### ISSUE TITLE
service worker is broken

### ISSUE THREAD

**Issue by mikejohn67** [ueno-llc/starter-kit-universally#97]
I have enabled the service worker from config file, But it looks like it is broken. Is here any solution for this problem.

![screenshot from 2018-04-02 03 24 10](https://user-images.githubusercontent.com/37987041/38177919-af730be6-3625-11e8-8f2f-cd515d471ec8.png)
![screenshot from 2018-04-02 03 25 01](https://user-images.githubusercontent.com/37987041/38177926-bff1483e-3625-11e8-9084-fc79082349f7.png)

**Comment by birkir** [comment]
This is definitely a bug, should be easily fixed. Thanks for the report!

**Comment by mikejohn67** [comment]
@birkir Thanks for quick response, Can you please give me guideline how to fix it, I tried it but could not succeed.

I am using this biolerplate in production & i am looking forward to this bug to fixed soon.
here is website https://ednsquare.com/

**Comment by birkir** [comment]
Bug is fixed!
Cool website! 🤘

**Comment by gufranmirza** [comment]
@birkir thanks,
Will update boilerplate soon.

**Comment by mikejohn67** [comment]
@birkir 
Getting this error when offline
![screenshot from 2018-04-03 22 25 22](https://user-images.githubusercontent.com/37987041/38263753-8650a128-378e-11e8-8a41-093a158ef7e9.png)

Service worker is being registered
![screenshot from 2018-04-03 22 29 12](https://user-images.githubusercontent.com/37987041/38263760-8d276b08-378e-11e8-8c1a-079c856edcca.png)

Its blocking menifest.json and its type is script (I think it should be type of menifest ) 
![screenshot from 2018-04-03 22 25 29](https://user-images.githubusercontent.com/37987041/38263768-944b0e9e-378e-11e8-92d8-127cff6cf9ec.png)

**Comment by birkir** [comment]
Ok this is a pretty big issue, you will need to disable the CSP hash rule for scripts until the issue is resolved.

**Comment by mikejohn67** [comment]
@birkir  CSP is disabled, Its still not working

![screenshot from 2018-04-07 18 27 07](https://user-images.githubusercontent.com/37987041/38455187-3be7459a-3a92-11e8-8e28-518b998b90d0.png)

Please let me know how to fix this, I need it urgently.
Thanks
